### ISSUE TITLE
Encryption key should be rotate-able

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11374]
Currently, the encryption key is tightly coupled to the system usage and cannot be changed/rotated without affecting users. This (inability to rotate the encryption key) is not a good security practice.

We need to adapt our practices such that the encryption key can be easily changed/rotated when needed. Based on what will happen if the encryption key is changed:
- [ ] Encrypted registration key for student/instructor in URLs: will be non-functional. This will be resolved by #11375.
- [ ] HMAC value for instructor institution in URLs: will be non-functional. This will be resolved by either #11362 or #11371.
- [x] Encrypted feedback response ID: not affected as the usage is localized (only when a page loads responses and sends back response-related entities)
- [x] State string for OAuth2: not affected as the usage is localized (only during the brief login period)
- [x] Browser cookie for user: not majorly affected as users simply will be unable to use their existing cookies and need to re-login
