### ISSUE TITLE
Notification Feature

### ISSUE THREAD

**Issue by fsgmhoward** [TEAMMATES/teammates#11572]
This issue keeps track of PRs related to the new Notification feature (a.k.a. Message of the Day). This new feature aims to provide a convenient way for the administrator(s) to disseminate information to users (including both students and instructors). More information can be found here: https://github.com/TEAMMATES/teammates/wiki/Message-of-the-Day

The tracking branch for this feature is [`notification-feature`](https://github.com/TEAMMATES/teammates/tree/notification-feature). PRs for this feature should be done against this branch. Guidelines for feature branch maintenance can be referred to the [Maintainer Guide](https://github.com/TEAMMATES/teammates-ops/blob/master/maintainer-guide.md#using-a-long-lived-feature-branch).

Task list (order following the milestones):
- [X] [Database Skeleton](https://github.com/TEAMMATES/teammates/pull/11575)
- [X] [GET route](https://github.com/TEAMMATES/teammates/pull/11625)
- [X] [POST route](https://github.com/TEAMMATES/teammates/pull/11620)
- [X] [Admin frontend page for viewing and creating notifications](https://github.com/TEAMMATES/teammates/pull/11623)
- [x] Frontend without mark-as-read feature
- [x] [Change of Account DB to store read status](https://github.com/TEAMMATES/teammates/pull/11643)
- [ ] Backend API to update read status
- [x] PUT route
- [X] [DELETE route](https://github.com/TEAMMATES/teammates/pull/11650)
- [x] Integration of update and delete page for Admin notification page
- [ ] Past notification page
- [ ] Frontend tests
- [x] Backend tests
    - [x] GET
    - [x] POST
    - [x] PUT
    - [x] DELETE
- Refactor unused code
    - [ ] `FieldValidator.java` `getInvalidityInfoForNotificationType` (enum will render null if invalid type)
    - [ ] `FieldValidator.java` `getInvalidityInfoForNotificationTargetUser` (same as above)

**Comment by fsgmhoward** [comment]
Task list (order following the milestones):
- [X] [Database Skeleton](https://github.com/TEAMMATES/teammates/pull/11575)
- [X] [GET route](https://github.com/TEAMMATES/teammates/pull/11625)
- [X] [POST route](https://github.com/TEAMMATES/teammates/pull/11620)
- [ ] [Admin frontend page for viewing and creating notifications **(pending for review)**](https://github.com/TEAMMATES/teammates/pull/11623)
- [ ] Frontend without mark-as-read feature
- [ ] [Change of Account DB to store read status **(pending for review)**](https://github.com/TEAMMATES/teammates/pull/11643)
- [ ] Backend API to update read status
- [ ] PUT route
- [ ] DELETE route
- [ ] Integration of update and delete page for Admin notification page
- [ ] Past notification page
- [ ] Frontend tests
- [ ] Backend tests
