### ISSUE TITLE
Usage statistics page for maintainers

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11618]
- **Environment**: live server at `V8.9.0`; feature is never present in the system nevertheless

**Description of feature/enhancement**

- Collect regular statistics of relevant usages such as new entities created, sessions ongoing, and emails sent
- The statistics are purely numerical and cannot be traced back to any user or user group
- Maintainers and admins will be able to view the statistics in a time-series graph
- NOT included: usage of machine resources such as CPU and RAM

**Justification**

- Maintainers and admins can see the usage trend and how they evolve over time
- The knowledge of usage trend can also be used to formulate deployment strategies such as idle time or replica numbers

**Steps**

- [x] Delete all meaningless data from the DB:
  - [x] Orphan courses, i.e. courses with no instructors
  - [x] Data inserted by legacy browser tests
  - [x] Sample courses belonging to users who requested account but never registered; this is no longer a problem since #11371, but the legacy mistake has resulted in tons of meaningless data now
- [x] Back-fill instructor's `createdAt` date
- [x] Back-fill student's `createdAt` date (entities from before Feb 2016 do not have this field)
- [x] ~Fix sample session's start/end/visible times (see #11626)~ Not to be done now
- [x] Back-fill account request entities based on sample courses
- [x] Create hourly cron job to collect statistics
- [x] Create page for maintainers and admins to view the statistics
- [x] Back-fill statistics data from 2016 afterwards
  - While we can back-fill data from the beginning of TEAMMATES (i.e. 2010), it does not value add as the usage pattern back then and the usage pattern right now is significantly different. For example, it took 7-8 years (mid 2018) to reach 10M responses mark, but only 3.5 years (end 2021) to reach 30M responses mark!
  - 2016 is chosen because more than 90% of the courses in TEAMMATES is created from 2016 onwards.

**Comment by wkurniawan07** [comment]
https://github.com/TEAMMATES/teammates/tree/11618-scripts

The scripts for the first round of data cleaning are ready. Order of usage:
- `DeleteOrphanCourses` to delete courses without instructors
- `DeleteTestCourses` to delete courses added by legacy tests
- `PopulateAccountRequestEntities` serves two functions:
  - to populate the AccountRequest entities based on past account requests
  - to delete sample courses belonging to users who never registered

**Comment by wkurniawan07** [comment]
All tasks are done and delivered. Epic is finished.
