### ISSUE TITLE
Request log statistics page for maintainers

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11763]
- **Environment**: live server at V8.14.1; feature is never present in the system nevertheless

**Description of feature/enhancement**

Similar to #11618 in spirit, but this time the statistics will be concentrated around request logs.

- Collect regular statistics of information obtained from request logs, such as:
  - User agents (to check the frequency of browser usage)
  - Web UI versions (to check the frequency of stale-cache users)
  - Response status (in particular, to check the frequency of 5XX errors)
  - HTTP referrers, without the query parameters (to check the frequency of page visits)
- Although the statistics are no longer purely numerical, they do not contain any sensitive/confidential information.
- Maintainers and admins will be able to view the statistics in a table (time-series graph does not really make sense as there are a lot of data points especially for user agents).
  - The table view will also be extended to the existing usage statistics page.
- Notably, these are information that are usually ingested and calculated by services such as LogStash or BigQuery, but until and if we are going to make use of such service, we will be building on our own as far as we can.
- STILL NOT included: usage of machine resources such as CPU and RAM.
  - The request log statistics can be seen as in-between, in a way.

**Steps**

- [ ] Support tabular view of statistics in usage statistics page
- [ ] Create hourly cron job to collect statistics
- [ ] Extend the usage statistics page to be able to query the new statistics objects

**Comment by samuelfangjw** [comment]
Closing for now, will be reopened when we are ready to tackle this properly.
