### ISSUE TITLE
Refactoring of sortable tables

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12329]
Sortable tables are used in several pages, but a fair number of them don't make use of the `sortable-table` component. Searching `sortable` amongst `.html` files should bring up these 10 (unlikely to be more, but best to do a more thorough search):

- [x] Extension confirm modal (Completed: #12556)
- [ ] Per question view responses
- [ ] Sessions recycle bin table
- [x] Sessions table (Completed: #12501)
- [x] Student list (Completed: #12539)
- [ ] Notifications table
- [ ] Copy instructors from other courses modal
- [ ] Instructor courses page
- [ ] Copy questions from other sessions modal
- [ ] Instructor session individual extension page

It would be good to refactor the above components to make use of the `sortable-table` component to avoid duplication. Some other components, like the contribution question statistics component and the MCQ question statistic component, already make use of that component, so they can be referenced.

**Comment by Sho-Shoo** [comment]
Hi! I would like to take this issue as a first-time contributor.

**Comment by weiquu** [comment]
Hi @Sho-Shoo, we normally recommend issues tagged with `good first issue` for first-time contributors. However, if you're confident of tackling this issue, you can go ahead and submit a PR for it (:

**Comment by mud1tx** [comment]
@weiquu Can you please describe the issue once again, I can work on this issue. One more thing what does `sortable-table` component do?

**Comment by weiquu** [comment]
Hi @mud1tx, you can find the `sortable-table` component files and look through them to see what they do and how they do it. As an overview, the `sortable-table` component, as the name suggests, is a sortable table. Do let me know if you run into any specific issues, and also detail your understanding and what you've tried so that I can better assist.

**Comment by mud1tx** [comment]
> Hi @mud1tx, you can find the `sortable-table` component files and look through them to see what they do and how they do it. As an overview, the `sortable-table` component, as the name suggests, is a sortable table. Do let me know if you run into any specific issues, and also detail your understanding and what you've tried so that I can better assist.

I will try working on it today and let you know about it.

**Comment by Zxun2** [comment]
Hello! I will like to try refactoring the sessions table component. Is that okay?

**Comment by domlimm** [comment]
@Zxun2 Hello! Feel free to submit a PR 👍🏻

**Comment by singhabhyudita** [comment]
Hi, I'll be taking up the Instructor courses page. Hope that's okay?

**Comment by weiquu** [comment]
> Hi, I'll be taking up the Instructor courses page. Hope that's okay?

Sure, do note the changes to the `sortable-table` component that was introduced in #12501

**Comment by domoberzin** [comment]
Helllo, could I work on the student list component?

**Comment by jasonqiu212** [comment]
> Helllo, could I work on the student list component?

Sure thing @domoberzin :) Do note the changes introduced by #12501

**Comment by RohithSurya** [comment]
Hi Guys!!
Letting you know I am working on refactoring notification tables 🙂.

**Comment by domoberzin** [comment]
Hi, just checking if this issue should be re-opened? Because the remaining subtasks have not yet been completed for the other pages

**Comment by weiquu** [comment]
Thanks @domoberzin! Good catch

**Comment by Surge747** [comment]
Hey I would like to work on this refactoring Issue
Could I be assigned to work on it?

**Comment by samuelfangjw** [comment]
Closing, see https://github.com/TEAMMATES/teammates/pull/14028#issuecomment-4709832158.
