### ISSUE TITLE
Custom Feedback Paths

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#5773]
The Custom Feedback Paths feature will allow for a finer customisation of feedback giver to feedback recipient feedback paths. Development will take place on the long-lived `custom-feedback-paths` branch. I will update this issue with references to the relevant PRs when the feature is completed.

Below lists the aspects involved in implementing the Custom Feedback Paths feature. Beside each aspect is a link to the relevant PR where applicable. Those that have a tick beside them have been merged into the `custom-feedback-paths` feature branch.

Main PR (#5850)
- [x] Frontend (#5777)
- [x] Storage and Retrieval (#5895)
- [x] Results (#5941)
- [ ] Sanitization and Validation (#6023)
- [x] Visibility (#6345)
- [x] Update and Delete Cascades (#6061)
- [ ] Testing (In progress)

**Comment by JosephineKwa** [comment]
@damithc would it be alright if I directly created PRs for the various aspects of the custom feedback paths feature as they are implemented, or would you prefer issues to be created for them?

**Comment by damithc** [comment]
Is this going to be a long lived branch? In that case, you can create PRs against that branch without having corresponding issues I guess. Use this issue number in all PR names with a prefix?
e.g.
`Add database support for custom feedback paths - part of #5773`

**Comment by damithc** [comment]
You can also add the parts as a checklist in the issue description (I've added a sample above)

**Comment by JosephineKwa** [comment]
Regarding the PR format, I was thinking of the following (similar to static analysis PRs):
1. Title of PRs: Custom Feedback Paths: {aspect}
2. Branch name: custom-feedback-paths-{aspect}
3. Merging will use the PR number instead of the issue number
{aspect} refers to which part of the custom feedback paths feature was implemented in the PR

**Comment by damithc** [comment]
Sure, we can follow the same.
