### ISSUE TITLE
Refactor and fix bugs for the whole log system

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6502]
Currently, these classes are involving in the log system and need to be re-examined.

- `ActivityLogEntry`
- `AdminLogQuery`
- `EmailLogEntry`
- `GaeLogApi`
- `Logger`
- `AdminEmailLogPageAction`
- `AdminEmailLogPageData`
- `AdminActivityLogPageAction`
- `AdminActivityLogPageData`

They're lacking consistency and documentation. To solve this, several sub-issues are needed to be solved (will update when necessary).

- [x] [#6503] Separate the UI and logic for `ActivityLogEntry`
- [x] [#6504] Use a more standard way to generate `ActivityLogEntry` or log message
- [x] [#6654] Complete AdminActivityLogPageActionTest
- [ ] [``] Create a template class for `statusToAdmin` in all `*Action` classes
- [ ] [``] Refactor `AdminEmailLogPageAction` and `AdminEmailLogPageData`
- [ ] [``] Add more test case of `AdminActivityLogPageUiTest`
- [x] [#6753] Separate the UI and logic for `EmailLogEntry`
- [x] [#6855] Implement AdminEmailLogPageActionTest
- [ ] [``] Refactor `AdminActivityLogPageAction` and `AdminActivityLogPageData`

- [ ] To discuss `// TODO: can move log verification in action test cases to `ActivityLogGeneratorTest` or remove
    // them totally`
- [ ] To discuss `// TODO rename the special INSTRUCTOR_FEEDBACK_STATS_PAGE to start with instructor`

Related issues (bugs):
 

- [x] [#5147] admin activity log search: earliest date and log count buggy
- [x] [#4436] admin activity log: user shown as 'unknown' for failed enroll action 
- [x] [#2834] adminActivityLog: instructorStudentRecordsPage links shown in the activity log loads an unformatted page
- [ ] [#2783] admin: can view activities related to a particular course or a session
- [ ] [#6711] Bug in generation of status message in AdminActivityLogPageAction.

@damithc Any bugs? The above is all I can find in the current issue tab.
@wkurniawan07 Is this acceptable? I almost finished the first two sub-issues.

**Comment by wkurniawan07** [comment]
@xpdavid I'm not entirely familiar with the logs feature myself, so I can only give suggestions based on the smaller issues. It will be good if the smaller issues are release-able on their own, i.e. if you can package e.g. the first two smaller issues to a new release and everything will still be working, and I trust that you can figure out ways to do that. I've done a refactoring on similar scale (maybe slightly bigger) before in #6223.

**Comment by wkurniawan07** [comment]
Will not be keeping this issue anymore as we are no longer maintaining a self-created logs page.
