### ISSUE TITLE
Devise a consistent error-handling mechanism

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6690]
Right now, our error-handling mechanism is sub-optimal because:
- They are all over the place. Where do we do `log.severe`? `assert *`? `throw new *Exception` (and which Exception to throw)? Where do we validate method parameters for non-nullity?
- ~They are often not helpful; `Supplied parameter was null` is as good as no error message (when the assertion is specifically checking for non-null) for the purpose of tracing/debugging.~ Already improved in V8.

We need to come up with a well-designed and well-documented error-handling mechanism.

Sub-issues (to be filled on the go):
- [x] Standardize usage of 403 errors (#11093)
- [x] Standardize usage of 409 errors (#11367)
- [x] Standardize usage of 404 errors
- [x] Standardize usage of 400 errors
- [ ] Add `log.severe` to actions resulting in `5XX` errors
- [ ] Document error-handling policies

**Comment by daongochieu2810** [comment]
@wkurniawan07 this seems to be quite old, what should we do with this issue?

**Comment by wkurniawan07** [comment]
@daongochieu2810 sorry I forgot to reply. I already have a full-blown plan for this; the task list in the issue description was only added last week.
