### ISSUE TITLE
Data Migration: Remove HTML sanitization in CourseAttributes

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7260]
Removing HTML sanitization in sanitizeForSaving in CourseAttributes as mentioned in #4588.

- [x] Removing html sanitization before saving while ensuring frontend works with both data formats (#7262)
- [x] Add data migration script for legacy data (#7571)
- [x] Run data migration on datastore (#7679)
- [ ] Remove code added to provide compatibility with legacy format

Script to remove after the issue is solved: DataMigrationForSanitizedDataInCourseAttributes

**Comment by damithc** [comment]
Looks like `Run data migration on datastore` done too?

**Comment by wkurniawan07** [comment]
Closing (see #4588 for reasons)
