### ISSUE TITLE
Set up foundation for front-end migration project

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#9079]
To kick off [this project](https://github.com/TEAMMATES/teammates/projects/4), some foundations need to be laid out first:
- [x] Step 1: Set up Angular 6 front-end project
  - Included: lint/build/test routine (including reliable code coverage), separate dev server from the back end, hot reload in development mode, source maps, minification when building for production usage
- [x] Step 2: Set up REST-ful back end servlet, ~possibly with the help of [Jersey](https://medium.com/@tejohnso/a-minimal-java-api-with-jetty-jersey-jackson-and-gradle-9842a145815e),~ and user authentication workflow
- [x] Step 3: Migrate few pages; concurrently, set up example of how migration for each page should be done systematically.

- [ ] Step 4 (can be deferred): Set up example tests, ranging from front-end component tests (with Karma/Jasmine), API endpoint tests (with TestNG), and E2E tests (with Selenium).

**Comment by wkurniawan07** [comment]
This can be considered as resolved.
