### ISSUE TITLE
Data Migration: Orphaned StudentProfile entity

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9089]
Data migration initiated by PR #7338.

- [x] Merged code that work for both the old and new versions of the data schema.
- [x] Released a version containing the above in [V5.109](https://github.com/TEAMMATES/teammates/releases/tag/V5.109).
- [x] Created a client script to migrate all data following the old schema to the new schema in PR #9044 .
- [x] Ran the script against the live site (done in #9076 ).
- [x] Removed the code that is specifically tailored for the old data schema in PR #9066 .

**Comment by xpdavid** [comment]
Done and released in V6.13.0
