### ISSUE TITLE
Migrate app pages to Angular, phase 1

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#9255]
V7 migration is finally underway!

For phase 1, we will be migrating "easy" pages, i.e. the ones that do not involve different question types (and for the ones that do, we will only migrate the page skeleton).

For each PR, we will observe the following:
- PR title: `[#9255] Migrate ... page to Angular`
- PR description: `Part of #9255` (the bot has been configured to accept this keyword)
- Expected works:
  - `Const.ViewURIs.*` -> `Const.WebPageURIs.*`
  - `Const.ActionURIs.*` -> `Const.ResourceURIs.*`
  - `ui.controller.*` -> `ui.newcontroller.*`
  - `ui.pagedata`, `ui.template` must not be used anymore
  - `test.action.*` -> `test.newaction.*`, i.e. API endpoints must be tested
  - `*.jsp`, `*.tag`, `*.js` to be migrated to Angular counterparts (`*.html`, `*.scss`, `*.ts`)
  - The page look-and-feel should be as close as possible to the original, with (most of) the differences attributed to Bootstrap upgrade
  - No need to write front-end tests (but you're very welcome to!), but make sure that the existing ones don't fail/regress
  - No need to migrate the browser/E2E tests, but don't delete the old one either and make sure they can still compile

Checklist:
- [x] Student home page
- [x] Student course details page
- [x] Student profile page
- [x] Student help page
- [x] Instructor home page
- [x] Instructor courses page
- [x] Instructor course details page
- [x] Instructor course edit page
- [x] Instructor course enroll page
- [x] Instructor course student details page
- [x] Instructor course student edit page
- [x] Instructor feedback sessions page
- [ ] Instructor student list page
- [x] Instructor search page (excluding feedback responses + comments)
- [x] Instructor student records page (excluding feedback submissions/responses + comments)
- [ ] Instructor help page (excluding question type-specific help contents)

Skeleton only:
- [x] Session submission page
- [ ] Session results page
- [ ] Instructor session results page
- [ ] Instructor search page (feedback responses + comments)
- [x] Instructor session edit page
- [ ] Instructor student records page (feedback submissions/responses + comments)
- [ ] Instructor help page (question type-specific help contents)

**Comment by wkurniawan07** [comment]
Phase 1 has been concluded. Not everything targeted has been migrated, but enough for us to move on to the next phase. Thanks for everyone who has contributed!
