### ISSUE TITLE
Migrate app pages to Angular, phase 2

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#9382]
Phase 2 of the V7 migration is underway.

Firstly, dealing with the missed pages/features of phase 1:
- [x] Instructor home page/feedback sessions page: remind particular students feature
- [x] Instructor home page/feedback sessions page: resend link to view result
- [x] Instructor sessions edit page: copy questions from other feedback session
- [x] Instructor course edit page: custom privilege settings
  - [x] Tidy up code
- [x] Student profile page: profile picture features
- [x] Rich-text editor integration
- [x] Instructor student list page
- [x] Instructor help page (minus components)
- [ ] Session results page + instructor search page (feedback responses) + instructor student records page (feedback responses)
- [x] Instructor session results page (skeleton only)
- [x] Instructor home page/feedback sessions page: download result (to be done with instructor session results page)

Secondly (contingent to the skeleton of session results page being migrated), migrating the different questions one by one:
- [x] Text (done as example)
- [x] Contribution (done as example)
- [x] Numscale
- [x] MCQ
- [x] MSQ
  - [x] Enable generatedOptionsFor in Submission page for MSQ/MCQ
- [x] Distribute points (among options)
- [x] Distribute points (among recipients)
- [x] Rank options
- [x] Rank recipients
- [x] Rubric

Thirdly (contingent to the skeleton of instructor help page being migrated):
- [ ] Implementing the different components in instructor help page
