### ISSUE TITLE
Add E2E testing to teammates pages in v7

### ISSUE THREAD

**Issue by jacoblipech** [TEAMMATES/teammates#9536]
Migrate end to end tests for all the pages below from v6 to v7

- [x] Student Home Page
- [x] Student Profile Page
- [x] Student Course Details Page
- [x] Admin Home Page
- [x] Admin Accounts Page
- [x] Admin Search Page
- [x] Admin Sessions Page
- [x] Instructor Home Page
- [x] Instructor Course Details Page
- [x] Instructor Courses Page
- [x] Instructor Course Edit Page
- [x] Instructor Course Enroll Page
- [x] Instructor Course Student Details Page
- [x] Instructor Course Student Edit Page
- [x] Instructor Search Page (ticked by default; see division of cases)
  - [x] Students table
  - [ ] Responses + response comments table
- [x] Instructor Student List Page
- [x] Instructor Student Records Page (ticked by default; see division of cases)
  - [x] Student details
  - [ ] Feedback responses given/received by student
- [x] Instructor Session Edit Page
- [x] Instructor Sessions Page
- [x] Instructor Session Result Page
- [x] Session Submission Page
- [x] Session Result Page
- [x] Course Join Page

**Comment by wkurniawan07** [comment]
While we can use the browser tests in V6 as reference, we need to significantly re-think how to structure the tests such that they are indeed E2E level. In V6 and before, there were way too many stuffs tested in the browser tests that should be tested in lower level. It does not help that our severe overuse of God mode has eroded the value of testing (now we can barely remember what to pay attention to for each HTML test file). Of course, to be fair, there are factors such as lack of supporting infrastructure.

**Comment by wkurniawan07** [comment]
This can be considered as done as we have sufficient E2E tests now.
