### ISSUE TITLE
Add L&P tests for backend endpoints

### ISSUE THREAD

**Issue by amrut-prabhu** [TEAMMATES/teammates#9646]
Performance issue-prone operations:

- [x] Instructor page: Enrolling students
- [ ] Instructor page: Viewing feedback session results by instructor
- [ ] Student page: Submitting a feedback session when the number of questions is large
