### ISSUE TITLE
Feedback Response Comment

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9769]
**Description of feature/enhancement**
In v6, there was a feature of commenting on feedback responses. This issue is to track the progress of adding the feature back to v7.

**Feature Specification**
- **Both student and instructor**
    - Add a comment to an MCQ and MSQ response in submission page
        - Able to add only one comment
    - Edit own comments
    - Delete own comments
- **Student**
    - View comments through results page
    - Comment on behalf of team
- **Instructor**
    - View comments through results page
        - In `? > ? > Question` view group, show comments by default under responses
        - In other views, comments are hidden. Comments can only be viewed after clicking the `Add comment` button under `Actions` header.
    - Add comments through results page on any question type
        - Able to add multiple comments
    - Change visibility options of comment

**TODO:**
- [x] Front-end
  - [x] Create comment editor component
  - [x] Create comment table component
  - [x] Create comment table
  - [x] Create service to fetch comments from back-end
  - [x] Add comment table to submission page (MCQ and MSQ from response giver)
  - [x] Add comment table to submission page (MCQ and MSQ on behalf of team)
  - [x] Add comment table to instructor results page
    - [x] `Question` and GQR RQG view groups
    - [x]  GRQ RGQ view groups
  - [x] Add comment table to student results page
- [x] Back-end
  - [x] Update relevant comment *Action classes
  - [x] Update ActionFactory
  - [x] Update RESULT/get to include comments
- [x] Miscellaneous
  - [x] Visibility options
  - [x] Prevent commenting on empty response

**Current issues:**
- [x] Comment giver name showing as email instead of name.
- [ ] <strike>Instructor being able to edit any comment that they can see. (design choice?)</strike>
- [x] In Instructor result view, the comment table is not immediately updated upon changes (Add/Update/Delete). The section card has to be closed and reopened for the changes to be reflected.
- [x] In Instructor result, GRQ and RGQ views, comment table should be collapsed if empty and expandable with a button.

**Comment by manzurayusup** [comment]
Hello, I see that some some boxes are unchecked. Are Current Issues section still up for grabs?

**Comment by xpdavid** [comment]
For up for grabs issue, we have a special label `firstTimer`. The issues are actually resolved in #9794
