### ISSUE TITLE
Standardize API endpoints

### ISSUE THREAD

**Issue by tiuweehan** [TEAMMATES/teammates#9940]
### Summary

Follow up from #9919 and #9937 

Most of the requests to backend are done using `HttpRequestService` and string literals within the components that require the data. There are a few problems with this:
1. API endpoints may change, requiring us to manually update all the string literals.
2. There may be methods in separate components essentially making the same requests, which is not very DRY
3. Coupling with `HttpRequestService` makes it hard to refactor if we ever need to change our mode of data retrieval.

#### Phase 1 (Student module) - Closed by #9951 
- [x] Create gradle task to generate API endpoints in the frontend using endpoints in the backend
- [x] Create a service / update existing services to make all HTTP requests            
- [x] Add new tests for services
- [x] Refactor existing components to use service and new types

#### Phase 2 (Instructor module)
- [ ] Create a service / update existing services to make all HTTP requests            
- [ ] Add new tests for services
- [ ] Refactor existing components to use service and new types

#### Phase 3 (Admin module and others)
- [ ] Create a service / update existing services to make all HTTP requests            
- [ ] Add new tests for services
- [ ] Refactor existing components to use service and new types

### Things to look into
- How to properly design & modularize the service. I am thinking of following the `ActionFactory` design
- Using gradle to automatically generate the request types from the existing ones in the backend

**Comment by tiuweehan** [comment]
Would like to work on this if possible :)

**Comment by hcwong** [comment]
👍 .  If you're going to this, could you also help to ensure that the special characters are escaped properly? This #9925 somewhat fixes but it could be better.

**Comment by xpdavid** [comment]
Great start, note that:

> Using gradle to automatically generate the request types from the existing ones in the backend

This is done in`./gradlew generateTypes`

> How to properly design & modularize the service. I am thinking of following the ActionFactory design

If you understand Angular service correctly, you can organize service and create `*.service` for them and Angular will do dependency injection for you.

This should be an epic issue. You should do step by step and maybe refer to the issue as `Part of XXX`.

I recommend to combine phase I & II together and separate tasks based on the API endpoints (as the API endpoints are also fixed).

**Comment by tiuweehan** [comment]
@hcwong 

> 👍 . If you're going to do this, could you also help to ensure that the special characters are escaped properly? This #9925 somewhat fixes but it could be better.

I'm not sure if we should include string validation as part of this service, as its primary purpose is to make API requests. Maybe there should be a separate service for string validation - What do you think?

@xpdavid 

> If you understand Angular service correctly, you can organize service and create *.service for them and Angular will do dependency injection for you.

If I understand this correctly, we should create a service for each endpoint? If that is the case, there will be a lot of files in the `services` directory - should we also modularize it?

> I recommend to combine phase I & II together and separate tasks based on the API endpoints (as the API endpoints are also fixed).

I will start with the API endpoints for students module first.  Thank you!

**Comment by xpdavid** [comment]
> If I understand this correctly, we should create a service for each endpoint? If that is the case, there will be a lot of files in the services directory - should we also modularize it?

Do you think it is better to create a service for each endpoint or create a service for a set of homogeneous endpoints (e.g. CRUD operations for an entity type)?

**Comment by tiuweehan** [comment]
Yup I think that makes more sense
